spring:
  datasource:
    url: jdbc:h2:mem:maindb

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

  sql:
    init:
      mode: always
      data-locations: classpath:/data.sql
      schema-locations: classpath:/schema.sql

  data:
    rest:
      base-path: /data-rest

management:
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  health:
    defaults:
      enabled: true
  endpoints:
    web:
      exposure:
        include: metrics, health, logfile

logging:
  file:
    name: books-log.log

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        slowCallDurationThreshold: 5s
        slowCallRateThreshold: 80
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      bookCircuitBreaker:
        baseConfig: default
      commentCircuitBreaker:
        baseConfig: default
        waitDurationInOpenState: 20s

